
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '../components/Footer'
import Menu from '@/components/menu/Menu'
import Hero from '@/components/Hero/Hero'
import TableIdContext from '@/providers/AppProvider'
import { tableIds } from '@/helpers/connect'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // Select table of next or public 
  // const tableId = tableIds.public;
  const tableId = tableIds.next;

  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        {/* <TableIdContext.Provider value={tableId}> */}
          {/* <Menu /> */}
          <Hero />
          {children}
          <Footer />
        {/* </TableIdContext.Provider> */}
      </body>
    </html>
  )
}
